FROM golang:1.14.3-alpine3.11 as builder

WORKDIR /go/src/soma
COPY ./src/soma/ .

RUN go test /go/src/soma
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w -extldflags "-static"' -o soma

FROM scratch
COPY --from=builder /go/src/soma /

CMD ["/soma"]